### ISSUE TITLE
Cannot add new projects as mentor

### ISSUE THREAD

**Issue by satyaakam** [JIITODC/JMoC-website#9]
I know folks must be working hard to get the functionality done this issue is just to track  it 

when i click on the adding project as a mentor http://jmoc.jodc.tech/project/new i get an error 
"Cannot GET /project/new"

**Comment by karandevtyagi** [comment]
@satyaakam  link is working.Please check it again.
![snapshot_of_addproject](https://user-images.githubusercontent.com/40595692/72076429-86632700-331b-11ea-93d3-a55a9b63839d.PNG)

**Comment by satyaakam** [comment]
Ok i was able to add a project , what next , will it be displayed somewhere ?

**Comment by karandevtyagi** [comment]
We are stilll receving projects from mentors and after a certain threshold we will display them on our website.
